// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/toheart/go-structure/internal/biz"
	"github.com/toheart/go-structure/internal/conf"
	"github.com/toheart/go-structure/internal/data"
	"github.com/toheart/go-structure/internal/server"
	"github.com/toheart/go-structure/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	v := service.NewHttpServiceList(greeterService)
	httpServer := server.NewHTTPServer(confServer, logger, v...)
	grpcServer := server.NewGRPCServer(confServer, logger, v...)
	v2 := server.NewServerList(httpServer, grpcServer)
	app := newApp(logger, v2)
	return app, func() {
		cleanup()
	}, nil
}
